baseURL = "https://serpentos.com/"
languageCode = "en-us"
title = "Serpent OS"
theme = "fresh"
copyright = "Copyright &copy; 2020 Serpent OS Developers<br />"

[params]
herotitle = "Under Heavy Development"
herolink = "https://github.com/serpent-linux/"
herolinktext = "Check our GitHub"
contact = "Send me a message and I will get back as soon as possible."
title = "SERPENT OS"

[permalinks]
    blog = "/blog/:year/:month/:day/:title/"

[menu]

    [[menu.main]]
        name = "Home"
        url = "/"
        weight = -3

    [[menu.main]]
        name    = "About"
        url     = "/about/"
        weight = -2

    [[menu.main]]
        name    = "Blog"
        url     = "/blog/"
        weight = -1

    [[menu.main]]
        name = "Team"
        url = "/team/"
        weight = 0

    [[menu.social]]
        name = "rss"
        url = "/blog/index.xml"
        pre = "<i class='fas fa-rss'></i>"
        weight = -1

    [[menu.social]]
        name = "irc"
        url = "irc://chat.freenode.net/#serpentOS"
        pre = "<i class='fas fa-hashtag'></i>"
        weight = -2

    [[menu.social]]
        name = "twitter"
        url = "https://twitter.com/SerpentLinux"
        pre = "<i class='fab fa-twitter'></i>"
        weight = -3

    [[menu.social]]
        name = "github"
        url = "https://github.com/serpent-linux"
        pre = "<i class='fab fa-github'></i>"
        weight = -4

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        privacyenhanced = true

[taxonomies]
    author = "authors"
    category = "categories"
    contributor = "contributors"
